easy_admin:
    site_name: 'Tutoract'
    design:
        brand_color: '#6b1710'
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id 
                    - email
                    - roles
                    - password
                    - createdAt
                    - updatedAt
                    - avatar
                    - nickname
                    - firstname
                    - lastname
                    - city
                    - linkedin_account
                    - twitter_account
                    - github_account
                    - promo
                    - techs
                    - events
                    - messages
                    - eventsOwned
        Tech:
            class: App\Entity\Tech
            list:
                fields:
                    - id 
                    - name
                    - description
                    - users
                    - events
            form:
                fields:
                    - name
                    - description
        Message:
            class: App\Entity\Message
            list:
                fields:
                    - id 
                    - content
                    - user
                    - event
            form:
                fields:
                    - content
                    - user
        Promo:
            class: App\Entity\Promo
            list:
                fields:
                    - id 
                    - name
                    - users
            form:
                fields:
                    - name
        Event:
            class: App\Entity\Event
            list:
                fields:
                    - id 
                    - createdAt
                    - updatedAt
                    - date
                    - description
                    - users
                    - tech
                    - owner
                    - studentLimit
                    
              
                    
                    

